### ISSUE TITLE
Upload data on a website?

### ISSUE THREAD

**Issue by firefoxlover** [jonathanklee/Sapio#15] opened 2023-08-08 01:26 UTC
Hi, great app, I have submitted all closed source apps I own to it. But now where is the data? I want to browse it on my Laptop too, and generally think it would be great to have it on a website.

Great project!

**Comment by berdosi** [comment] 2023-08-10 21:30
Until there is one, the API endpoints are [defined here](https://github.com/jonathanklee/Sapio/blob/cbec5c0d44c93e1461b700c3d5dabd436d30f90a/app/src/main/java/com/klee/sapio/data/RetrofitClient.kt#L83), e. g. this is one application's "data sheet": https://sapio.ovh/api/sapio-applications/2001

NB Using the undocumented JSON is not particularly user-friendly, and, while it would be nice to publish the crowdsourced data, poking the API is not how it was intended to be used.

**Comment by jonathanklee** [comment] 2023-08-23 10:16
@berdosi @firefoxlover I wouldn't mind if anyone wants to start building a website on top of the data.

**Comment by jonathanklee** [comment] 2024-07-18 18:06
Closing this because API is now available if anyone wants to create a website.

**Closed by jonathanklee** 2024-07-18 18:06 UTC
